### ISSUE TITLE
about scape_remsh dataset

### ISSUE THREAD

**Issue by zjisuccess** [LIX-shape-analysis/SURFMNet#1]
Thanks for your contribution for the shape analysis with the deep learning concepts,but when i check the scape_remesh dataset,i find the mesh051 is lost.can you upload it again? thanks for your reply.

**Comment by LIX-shape-analysis** [comment]
Hi. Thank you for your interest. Indeed, as far as I'm aware most versions
of the SCAPE dataset have mesh051 missing. For instance, the Blended
intrinsic maps benchmark:

http://www.vovakim.com/projects/CorrsBlended/doc_data.html

also does not contain mesh051. I'm not sure why, but perhaps there was an
error in that particular mesh? We did not have this mesh in any of the
datasets.

**Comment by zjisuccess** [comment]
thanks for your reply in time.how do you try the visualization of the test results?when i visualize it,but it is terrible.

**Comment by bach-zouk** [comment]
Hi,

there is a separate matlab code for reproducing the avg. geodesic plots and also visualizing the matches. We will upload it in couple of days along with the ground truth. Feel free to create a separate issue for that.
