### ISSUE TITLE
original mesh data

### ISSUE THREAD

**Issue by lixiang-ucas** [LIX-shape-analysis/SURFMNet#3]
Dean Jean, thanks for sharing your wonderful work. I've found the processed shot descriptors of each dataset mentioned in your paper, but I didn't find the corresponding mesh data. Would you please also share the original mesh data?

**Comment by bach-zouk** [comment]
Hi,

I will update the *prepare_data.sh* in couple of hours so that an OFF folder including the mesh can be downloaded along with the already existing processed data.

Abhishek
