### ISSUE TITLE
How to get target_evecs_trans in .mat file

### ISSUE THREAD

**Issue by JingyiLi-612** [LIX-shape-analysis/SURFMNet#4]
Hello,
I am trying to run SURFMNet on my own dataset, and I have finished calculating shot descriptor and evecs. But I faced difficulties when calculating target_evecs_trans. I don't understand how to transpose the evecs with **mass matrix correction**. 
Could you please explain it or share the pre-processing code? Thank you a lot!

**Comment by JingyiLi-612** [comment]
Oh, I got it! 
target_evecs_trans = transpose(target_evecs) * A
where A is the diagonal matrix of vertex area elements.
We do it because transpose(phi) * A * phi  = I.

**Comment by cathylacus** [comment]
> Hello,
> I am trying to run SURFMNet on my own dataset, and I have finished calculating shot descriptor and evecs. But I faced difficulties when calculating target_evecs_trans. I don't understand how to transpose the evecs with **mass matrix correction**.
> Could you please explain it or share the pre-processing code? Thank you a lot!

Hello，I want to use my own dataset calculating shot descriptor and evecs，But I don't know how to calculate。Could you please share your code to me？ Thank you！

**Comment by bach-zouk** [comment]
Please check this script where from line 85 you can compute laplacian eigen vectors. https://github.com/LIX-shape-analysis/GeomFmaps/blob/master/MATLAB_Tools/createDataset_Shrec.m

For shot, there is an open source code which runs on windows only.

**Comment by JingyiLi-612** [comment]
@cathylacus For shot, you can use MEX file functions on MATLAB, then you can use shot function on any operating systems. [the documentation is here](https://ww2.mathworks.cn/help/matlab/call-mex-file-functions.html?lang=en)
