### ISSUE TITLE
Original meshes for scape_remeshed

### ISSUE THREAD

**Issue by michaelzhou0723** [LIX-shape-analysis/SURFMNet#5]
Hi! I downloaded the scape_r dataset but it only has SHOT descriptors. Could you also provide the corresponding mesh data?

**Comment by bach-zouk** [comment]
Sure, tomorrow. just that it takes a lot of storage.

**Comment by bach-zouk** [comment]
https://drive.google.com/file/d/1mmKr0AphJ3MKn5oQPQhjaZ5E1k64oQvi/view?usp=sharing

**Comment by michaelzhou0723** [comment]
> https://drive.google.com/file/d/1mmKr0AphJ3MKn5oQPQhjaZ5E1k64oQvi/view?usp=sharing

Much thanks!
